import Head from "next/head";

export default function Home({ users }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {users.map((user) => (
          <div key={user.id}>
            <h2>{user.name}</h2>
          </div>
        ))}
      </main>
    </>
  );
}

// getting data dynamically from server on each request
export async function getServerSideProps() {
  const data = await fetch("https://json-placeholder.mock.beeceptor.com/users");
  const res = await data.json();
  console.log(res)
  return {
    props: {
      users: res
    }
  }
}

// getting data using api but it will call only once like for home,contact about pages
// export async function getStaticProps() {
//   const data = await fetch("https://json-placeholder.mock.beeceptor.com/users");
//   const res = await data.json();
//   return {
//     props: {
//       users: res
//     }
//   }
// }

// getting data using api but it changes aftrr every fixed time interval
// import path from 'path';
// import fs from 'fs/promises';
// export async function getStaticProps() {
//   const filePath = path.join(process.cwd(), "");
//   const jsonData = await fs.promises.readFile(filePath);
//   const res = JSON.parse(jsonData);
//   return {
//     props: {
//       res: res
//     },
//     revalidate: 10 // it will update the data after every 10 seconds
//   }
// }
